# Jobs used to create and destroy Azure resources
# .github/example-workflows/spinup-destroy.yml
name: Configure Azure environment
 
on:
 pull_request:
   types: [labeled]
 
env:
 IMAGE_REGISTRY_URL: ghcr.io
 AZURE_RESOURCE_GROUP: cd-with-actions
 AZURE_APP_PLAN: actions-ttt-deployment
 AZURE_LOCATION: '"Central US"'
 AZURE_WEBAPP_NAME: <username>-ttt-app
 
jobs:
 setup-up-azure-resources:
   runs-on: ubuntu-latest
 
   if: contains(github.event.pull_request.labels.*.name, 'spin up environment')
 
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
 
     - name: Azure login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
